name: Build and push Node.js Docker image to DockerHub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_SECRET }}

    - name: Build and push to DockerHub
      uses: docker/build-push-action@v5
      with:
        context: .  # Build context (directory with Dockerfile)
        platforms: linux/amd64,linux/arm64  # Multi-platform build
        push: true
        tags: fathhhhh/gapscrap:latest